@url = http://localhost:4400

###
GET {{url}}/photosapi

###

GET {{url}}/photosapi/7

###

GET {{url}}/employeesapi

###

GET {{url}}/employeesapi/2


###

POST {{url}}/login
//Do not forget to add two lines
Content-Type: application/json


{
    "email": "sachi@vanarts.com",
    "password": "1"

}


###

POST {{url}}/signUp
Content-Type: application/json


{
    "user_name":"hello",
    "email":"hello@gmail.com",
    "password":"11111"
}


###

PUT {{url}}/updateUser 
Content-Type: application/json

{
"UserID": 10,
 "email": "test",
  "password": "111111"
}

// names need to match with the names used for the database. 


    

###

GET {{url}}/user/10
