@url = http://localhost:4400

GET {{url}}/updateCrud/2




###

PUT {{url}}/updateCrud
Content-Type: application/json

{
    "id":"2",
    "input":"changed again"

}

###

POST {{url}}/newCrudData
Content-Type: application/json

{
    "input":"testing"
}

###
GET {{url}}/allCrudData


###
POST {{url}}/updateCrud
Content-Type: application/json


{
      "id": "1",
    "input": "sachi@vanarts.com"
  

}





###
GET {{url}}/photosapi

###

GET {{url}}/photosapi/7

###

GET {{url}}/employeesapi

###

GET {{url}}/employeesapi/2


###

POST {{url}}/login
//Do not forget to add two lines
Content-Type: application/json


{
    "email": "sachi@vanarts.com",
    "password": "1"

}


###

POST {{url}}/signUp
Content-Type: application/json


{
    "user_name":"hello",
    "email":"hello@gmail.com",
    "password":"11111"
}


###

PUT {{url}}/updateUser 
Content-Type: application/json

{
"UserID": "1",
 "email": "test test",
  "password": "9999999"
}

// names need to match with the names used for the database. 


    

###

GET {{url}}/user/12


###

DELETE {{url}}/deleteuser/10
